### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by tin2tin** [britalmeida/edit_breakdown#1]
![image](https://user-images.githubusercontent.com/1322593/92326436-881fee80-f052-11ea-97f9-17774673158d.png)

**Comment by britalmeida** [comment]
Hello!
There isn’t much to go on just from a picture, but I think that is caused by the add-on folder name. Locally I’ve called it ”edit_breakdown” and only added the “blender_addon_” prefix on github.

That said, this add-on is barely a proof of concept yet. I don’t know what your goals are with it, but at the moment there are no usage instructions or even a working usage flow. That folder with pictures that is triggering the error will be removed.

**Comment by tin2tin** [comment]
No goal. Just trying to help out.

**Comment by tin2tin** [comment]
Nb. you'll still need to rename the folder inside the github code zip to ”edit_breakdown” in order to avoid this error: https://github.com/britalmeida/edit_breakdown/archive/refs/heads/master.zip

Currently, Sync Edit Breakdown doesn't do anything visible(no thumbnails appear).

If you need to quickly generate cuts in a strip, for testing your add-on, you can grab my shot detection add-on: https://github.com/tin2tin/shot_detection

**Comment by britalmeida** [comment]
Hello, github seems to append the branch name when downloading the code as a zip.
I hadn't noticed that, will think of a fix.

The usability of this add-on is still being prototyped. It needs a script to initialize content and there are no usage instructions yet.
